name: CI - Linting

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Linters
      run: |
        npm install -g htmlhint stylelint stylelint-config-standard

    - name: Run HTMLHint
      run: htmlhint "**/*.html"

    - name: Run Stylelint
      run: stylelint "**/*.css"
